version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        environment:
            - PORT=${PORT}
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5433
            - DB_DATABASE=laravel
            - DB_USERNAME=postgres
            - DB_PASSWORD=secret
        depends_on:
            - db

    nginx:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - app

    db:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_DB: first
            POSTGRES_USER: baba
            POSTGRES_PASSWORD: Sidy2002
        ports:
            - "5434:5432"
        networks:
            - laravel_network
        volumes:
            - postgres_data:/var/lib/postgresql/data

networks:
    laravel_network:
        driver: bridge

volumes:
    postgres_data: {}
