version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
                - storage:/var/www/html/storage

        networks:
            - app-network
        env_file:
            - .env

    webserver:
        image: nginx:alpine
        container_name: nginx-webserver
        restart: unless-stopped
        ports:
            - "8000:8024"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: postgres:13
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5433:5432"  # Changer le port hôte à 5433
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis-cache
        restart: unless-stopped
        ports:
            - "6380:6379"  # Modifié le port hôte à 6380
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
